### ISSUE TITLE
PaginationComp calling hooks in different orders on each render, causing Chakra-UI toast issues.

### ISSUE THREAD

**Issue by nfurbeyr** [anubra266/choc-paginator#2]
Whenever this Pagination component is rendered within my app, the following error is logged to the console:

_Warning: React has detected a change in the order of Hooks called by PaginationComp. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks._

For some reason, this is interfering with the ability to use chakra-ui's Toast component, to the point that the toast is not shown at all.

The following error is reported when attempting (and failing) to show toast:

_Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method._

Is this a known issue? Would be great to see this fixed.

**Comment by anubra266** [comment]
Will work on it ASAP.

**Comment by anubra266** [comment]
This package was written with an old Chakra UI API, so there were breaking changes to work on, so I rewrote it also using typescript this time. Recently learnt it. 😃
So you can install the latest now. And confirm if there are still any errors.

I also opened a codesandbox [here](https://codesandbox.io/s/choc-ui-packages-codesandbox-forked-85xpd?file=/src/App.js), change the pages to confirm that the toast is also working well. 

Thanks!

**Comment by anubra266** [comment]
Closing this since there's been no reply for a week.
